export const tags = [
	'react',
	'javascript',
	'css',
	'html',
	'web development',
	'web design',
	'nodejs',
	'express',
	'nextjs',
	'php',
	'laravel',
	'python',
	'ux',
	'ui',
	'machine learning',
	'app development',
	'java',
	'c++',
	'c#',
	'kotlin',
	'go',
	'rust',
	'c',
	'perl',
	'ruby',
	'financial',
	'health',
	'technology',
	'science',
	'lifestyle',
	'travel',
	'food',
	'fitness',
	'education',
	'fashion',
	'business',
	'marketing',
	'parenting',
	'entertainment',
	'career',
	'gaming',
	'art',
	'music',
	'politics',
	'environment',
	'self-improvement',
	'psychology',
	'history',
	'philosophy',
	'religion',
	'literature',
	'angular',
	'vuejs',
	'flutter',
	'devops',
	'docker',
	'kubernetes',
	'aws',
	'azure',
	'gcp',
	'big data',
	'data science',
	'artificial intelligence',
	'deep learning',
	'blockchain',
	'cryptocurrency',
	'cybersecurity',
	'robotics',
	'internet of things',
	'augmented reality',
	'virtual reality',
	'quantum computing',
	'biotechnology',
	'nanotechnology',
	'renewable energy',
	'climate change',
	'social media',
	'content creation',
	'influencer marketing',
	'e-commerce',
	'sustainability',
	'urban planning',
	'architecture',
	'photography',
	'videography',
	'cinematography',
	'graphic design',
	'user experience',
	'user interface',
	'networking',
	'cloud computing',
	'software engineering',
	'data engineering',
	'product management',
	'project management',
	'human resources',
	'customer service',
	'sales',
	'investing',
	'economics',
	'personal finance',
	'real estate',
	'legal',
	'biography',
	'poetry',
	'drama',
	'short stories',
	'novels',
	'theatre',
	'animation',
	'sculpture',
	'painting',
	'calligraphy',
	'opera',
	'jazz',
	'classical music',
	'rock music',
	'pop music',
	'hip hop',
	'electronic music',
	'folk music',
	'world music',
	'mythology',
	'folklore',
	'ancient history',
	'modern history',
	'cultural studies',
	'linguistics',
	'translation',
	'ethics',
	'metaphysics',
	'epistemology',
	'logic',
	'aesthetics',
	'comparative religion',
	'mythology',
	'cultural anthropology',
	'archaeology',
	'astrophysics',
	'genetics',
	'neuroscience',
	'astronomy',
	'geology',
	'marine biology',
	'zoology',
	'botany',
	'paleontology',
	'meteorology',
	'horticulture',
	'organic farming',
	'permaculture',
	'sociology',
	'gender studies',
	'media studies',
	'film studies',
	'sports science',
	'kinesiology',
	'veterinary science',
	'epidemiology',
	'public health',
	'gerontology',
	'toxicology',
	'criminology',
	'forensic science',
	'materials science',
	'industrial design',
	'textile design',
	'interior design',
	'landscape architecture',
	'urban studies',
	'regional planning',
	'public administration',
	'social work',
	'library science',
	'archival science',
	'museum studies',
	'bibliography',
	'philology',
	'semiotics',
	'psycholinguistics',
	'sociolinguistics',
	'anthropological linguistics',
	'cognitive science',
	'education technology',
	'instructional design',
	'distance learning',
	'special education',
	'counseling',
	'clinical psychology',
	'occupational therapy',
	'physical therapy',
	'speech therapy',
	'nutrition',
	'dietetics',
	'culinary arts',
	'hospitality management',
	'tourism management',
	'event management',
	'aviation',
	'aerospace engineering',
	'mechanical engineering',
	'electrical engineering',
	'civil engineering',
	'chemical engineering',
	'biomedical engineering',
	'nuclear engineering',
	'petroleum engineering',
	'systems engineering',
	'industrial engineering',
	'mining engineering',
	'logistics',
	'supply chain management',
	'quality control',
	'operations management',
	'human-computer interaction',
	'information systems',
	'bioinformatics',
	'computational biology',
	'game design',
	'game development',
	'esports',
	'sound engineering',
	'music production',
	'audio engineering',
	'music theory',
	'ethnomusicology',
	'music therapy',
	'creative writing',
	'screenwriting',
	'playwriting',
	'poetry writing',
	'novel writing',
	'comic book writing',
	'illustration',
	'concept art',
	'digital painting',
	'animation',
	'3D modeling',
	'VFX',
	'storyboarding',
	'choreography',
	'dance studies',
	'acting',
	'theater production',
	'film directing',
	'cinematography',
	'film editing',
	'documentary filmmaking',
	'photography',
	'photojournalism',
	'fine art photography',
	'street photography',
	'portrait photography',
	'landscape photography',
	'wildlife photography',
	'fashion photography',
	'sports photography',
	'astrophotography',
	'time-lapse photography',
	'macro photography',
	'architectural photography',
	'aerial photography',
	'photo editing',
	'darkroom techniques',
	'learning',
	'programming',
	'coding',
];

